version: 2
registries:
  npm-registry-npm-pkg-github-com-hideo54:
    type: npm-registry
    url: https://npm.pkg.github.com/hideo54
    username: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_HIDEO54_USERNAME}}"
    password: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_HIDEO54_PASSWORD}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  assignees:
  - hideo54
  registries:
  - npm-registry-npm-pkg-github-com-hideo54
